### ISSUE TITLE
Project maintenace

### ISSUE THREAD

**Issue by karneaud** [LiamMartens/xTend#10]
Stumbled upon your website and now your github. Your framework looks good. Hoping to put it to good use. How is it with support for JWT and JSON?

**Comment by LiahMartens** [comment]
Well JSON support is just as good as PHP is with JSON really and the framework hasn't been properly updated in quite a long time due to lack of time really :( so not sure how useful it will be to you

**Comment by karneaud** [comment]
Maaannn...that is a bummer. Was looking forward to trying it out. I build a lot of micro to medium RIAs so I'm always on the look out for simple frameworks. I stumbled upon your website and thought you had some interesting work. Hoping to collaborate or work with some of your stuff.
